dependencies:
  # - <organization(github account)/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
dotenv: .env
networks:
  default: development
  mainnet:
    verify: False
  rinkeby:
    verify: False
  kovan:
    verify: False
  polygon:
    verify: False
wallets:
  mainnet:
    from_key: ${PRIVATE_KEY_MAIN}
  rinkeby:
    from_key: ${PRIVATE_KEY_TEST}
  kovan:
    from_key: ${PRIVATE_KEY_TEST}
  polygon:
    from_key: ${PRIVATE_KEY_MAIN}
